openapi: 3.0.1
info:
  title: AccruentInventoryControl.API
  version: '1.0'
paths:
  /api/v1/InMemoryDatabaseInitializer:
    get:
      tags:
        - InMemoryDatabaseInitializer
      responses:
        '200':
          description: Success
  /api/v1/Product:
    get:
      tags:
        - Product
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
  /api/v1/Report/WarehouseTransaction:
    post:
      tags:
        - Report
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WarehouseTransactionReportRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/WarehouseTransactionReportRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/WarehouseTransactionReportRequest'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionReportResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionReportResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionReportResponse'
  /api/v1/WarehouseTransaction:
    get:
      tags:
        - WarehouseTransaction
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionResponse'
    post:
      tags:
        - WarehouseTransaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WarehouseTransactionRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/WarehouseTransactionRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/WarehouseTransactionRequest'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/WarehouseTransactionResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/WarehouseTransactionResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/WarehouseTransactionResponse'
  /api/v1/WarehouseTransaction/{id}:
    get:
      tags:
        - WarehouseTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseTransactionResponse'
components:
  schemas:
    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
      additionalProperties: false
    WarehouseTransactionReportRequest:
      required:
        - date
      type: object
      properties:
        date:
          type: string
          format: date-time
        productCode:
          maxLength: 255
          type: string
          nullable: true
      additionalProperties: false
    WarehouseTransactionReportResponse:
      type: object
      properties:
        productCode:
          type: string
          nullable: true
        date:
          type: string
          format: date-time
        warehouseTransactions:
          type: array
          items:
            $ref: '#/components/schemas/WarehouseTransactionResponse'
          nullable: true
        balance:
          type: integer
          format: int32
      additionalProperties: false
    WarehouseTransactionRequest:
      required:
        - productCode
        - quantity
        - type
      type: object
      properties:
        productCode:
          maxLength: 255
          minLength: 1
          type: string
        type:
          minLength: 1
          pattern: ^(inbound|outbound)$
          type: string
        quantity:
          maximum: 2147483647
          minimum: 1
          type: integer
          format: int32
      additionalProperties: false
    WarehouseTransactionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        product:
          $ref: '#/components/schemas/ProductResponse'
        quantity:
          type: integer
          format: int32
        type:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
        date:
          type: string
          format: date-time
        previousQuantity:
          type: integer
          format: int32
        totalQuantity:
          type: integer
          format: int32
      additionalProperties: false
